[project]
name = "learn-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Josiah Nyamai", email = "mungutijosiah1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dbt-core>=1.12.3",
    "dbt-databricks>=1.12.5",
]

[project.scripts]
learn-dbt = "learn_dbt:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
