dbt_tutorial:
  outputs:
    dev:
      catalog: bronze_layer
      host: dbc-ee0ecd81-a162.cloud.databricks.com
      http_path: /sql/1.0/warehouses/41f5cb30b1ba136c
      schema: source1
      threads: 1
      token: 
      type: databricks
  target: dev
